### ISSUE TITLE
Only Oldest Version Opens For Me

### ISSUE THREAD

**Issue by OldClassicGamer** [SenZmaKi/Senpwai#20]
Not sure why but it seems only the initial 2.0.0 version works for me.
All others simply refuse to run. Any idea why?

**Comment by SenZmaKi** [comment]
Anything I think of will just be guessing. What OS are you running on and have you tried to [building from source](https://github.com/SenZmaKi/Senpwai?tab=readme-ov-file#building-from-source)

**Comment by OldClassicGamer** [comment]
> Anything I think of will just be guessing. What OS are you running on and have you tried to [building from source](https://github.com/SenZmaKi/Senpwai?tab=readme-ov-file#building-from-source)

I am using Windows 10.
I have not tried building from a source as I am not skilled to do such a thing.
One thing I noticed is that when 2.0.0 (the version whose installer works for me) is installed compared to other versions, it includes many more files in the install folder (those that end with .py).

I suspect the absence of those files in later versions has to do something with why it won't run for me.
Is there any way you can make a new version and structure the installer to include those files .py files from version 2.0.0?

**Comment by SenZmaKi** [comment]
Those files were included cause that version was using a separate tool to bundle the code into an executable but the problem is that tool is popular so malware developers use it too so windows thought the app was malware so I had to switch to a different less popular bundling tool.

Install the [latest version](https://github.com/SenZmaKi/Senpwai/download/releases/latest/Senpwai-setup.exe) run it, then press `win + r` and type `%localappdata%/Senpwai` then press enter, it should open a folder with a file named `errors.log` (not `error-logs.txt` this one is for version 2.0.0) send the file here or copy paste its contents here

Building from source isn't that hard after you install python and git it's basically just copy pasting the command into Command Prompt and running it, I can even walk you through the process on [discord](https://discord.com/invite/e9UxkuyDX2). This is the fastest way for us to find a solution since we will know exactly where it is crashing then we can fix it.

**Comment by OldClassicGamer** [comment]
It seems I managed to solve the issue, although on very unusal way.
I tried to build from the source following instructions.
My computer had Python but some older version so I downloaded both Python 3.11 and Git which I also did not have.
I almost managed to build from source but at the very last step with command "pip install cx_freeze==6.15.10 && python setup.py build", I kept getting error which said "TypeError: 'set' object is not subscriptable in Python".
However, I tried now to once again use .exe installer and it worked!
So whatever I did with attempting to build from source and installing newer Python and Git, it seems to have worked.
My issue can be considered resolved.

**Comment by SenZmaKi** [comment]
Lol nice work, computers are weird. I think for the build error the command was using your old python version since according the your computer it came first so it favoured it over the latest version, so you got that syntax error cause newer versions have different syntax.  The simplest way to fix it is to uninstall the old python.
