### ISSUE TITLE
Defender blocked the download

### ISSUE THREAD

**Issue by folliejester** [SenZmaKi/Senpwai#63]
Trojan:Win32/PhonzyA!ml
![image](https://github.com/user-attachments/assets/5080be7f-242e-4d0d-a4b0-7216c21aa894)

**Comment by SenZmaKi** [comment]
Message copy pasted from the [discord server](https://discord.gg/invite/e9UxkuyDX2)


@everyone

Apologies for the everyone ping, but I want to address the recent virus reports.

Many antivirus programs flag anything that appears suspicious, better safe than sorry. Since Senpwai is not a signed application (signing applications costs money and this is a free and open source program), it’s automatically flagged by Windows Defender. Additionally, it’s written in Python, a language widely used by developers, including those who create malware, as it’s the second most popular programming language. 

It's like assuming everyone that wears cloths is a thief since every thief you've encountered wears cloths but in actuality every human being does so unless you're a weirdo.

The most "virus-like" thing Senpwai does is install FFmpeg if you don’t already have it and you wish to use HLS mode. Even then, this only happens with your consent.

Every line of code in Senpwai is publicly available on the [GitHub repository](https://github.com/SenZmaKi/Senpwai). You can even build it from source yourself, and [there’s a guide](https://github.com/SenZmaKi/Senpwai?tab=readme-ov-file#building-from-source) for doing so.

I indexed the repository and prompted GitHub copilot on whether or not Senpwai is a virus, here is the response. Take in mind this could be entirely fake as I could have just fabricated it using inspect element.

![image](https://github.com/user-attachments/assets/5835f8c4-b0ca-48dc-9d8a-9e8bd3c13a2c)


Further more here are some virus total scans of  [senpwai setup](https://www.virustotal.com/gui/file/306bb343152b9591935ea6328fd8d783dc31d909f0954c81ba7088112f551e4a) (7/70 flags) and of [senpwai](https://www.virustotal.com/gui/file/979094a8092cb71e36a574cc877c73c26c5acde258eb5d526fc66d534a5447e8) (1/53 flags), both v2.1.13. For contrast here are some scans of [hatt](https://github.com/FrenchGithubUser/Hatt) another popular free and open source unsigned application, [hatt installer](https://www.virustotal.com/gui/file/52af9190a47efe33841c5619beb09f9731ed764145ccc3ddc5f17eda1abb511b) (36/73 flags), [hatt](https://www.virustotal.com/gui/file/46fdead1c40748bd5fb71e267f57da17cc927e78dc8f2265de7f593e9f38690f) (20/75 flags), both v0.3.5.

**Comment by foxtbirdy** [comment]
This is a false flag. I run Senpwai on Linux and also performed a VirusTotal scan.
If you are still unsure, just run the cli version.
